In [2]:
import sys 
import numpy as np

In [3]:
#Define A and B as an array with values
a = np.array ([1,2,3,4,5,6,7,8])
b = np.array ([4,0.5,4.5,6.5,6.8,9.8])


In [4]:
a[0], a[4], b[2], b[4]

(1, 5, 4.5, 6.8)

In [5]:
a[0:], b[3:]

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([6.5, 6.8, 9.8]))

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
b

array([4. , 0.5, 4.5, 6.5, 6.8, 9.8])

In [8]:
a.dtype

dtype('int64')

In [9]:
#Different type because of values in the B array 
b.dtype


dtype('float64')

In [10]:
A = np.array([
    [1,2,3], [4,5,6]])

In [11]:
A.shape

(2, 3)

In [12]:
#Total dimensions 
A.ndim

2

In [13]:
#Total value 
A.size

6

In [14]:
B = np.array ([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [15]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
B.shape

(2, 2, 3)

In [17]:
B.ndim

3

In [18]:
B.size

12

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
#Get specific values
a[1,5]

13

In [21]:
a[1,-2]

13

In [23]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
#Get a specific column
a[:,0]

array([1, 8])

In [26]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Initialize different types of arrys

In [27]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
#Any other number
np.full((2,5), 89, dtype= 'float32')

array([[89., 89., 89., 89., 89.],
       [89., 89., 89., 89., 89.]], dtype=float32)

In [35]:
#Full_like (keeps the shape but can change rest)
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [38]:
#Random decimal numbers
np.random.rand(3,4,5)

array([[[0.23277756, 0.63552572, 0.91479684, 0.70033467, 0.41352468],
        [0.73886728, 0.69051978, 0.24747048, 0.36606802, 0.28088253],
        [0.69646833, 0.86428256, 0.10245616, 0.034448  , 0.27474741],
        [0.75014742, 0.0867775 , 0.06907479, 0.72203706, 0.03329385]],

       [[0.67726234, 0.39278167, 0.23980767, 0.57710384, 0.0058289 ],
        [0.04174829, 0.28381583, 0.48457236, 0.41184509, 0.79048875],
        [0.76223394, 0.23391675, 0.44008317, 0.18102736, 0.83175228],
        [0.05856405, 0.77582008, 0.04278298, 0.91906825, 0.13665031]],

       [[0.79836355, 0.83431446, 0.52455938, 0.11892502, 0.24745977],
        [0.16680401, 0.75057691, 0.80773071, 0.88750142, 0.20014526],
        [0.03674313, 0.47354897, 0.710454  , 0.82751951, 0.97848625],
        [0.84377731, 0.79443163, 0.29688   , 0.3156652 , 0.37077141]]])

In [44]:
#Random Integar number
np.random.randint(9, size=(4,4,5,6))

array([[[[6, 6, 3, 4, 6, 4],
         [5, 0, 2, 8, 7, 1],
         [8, 1, 7, 3, 8, 7],
         [4, 0, 3, 6, 7, 5],
         [1, 0, 3, 5, 2, 1]],

        [[1, 0, 2, 3, 6, 8],
         [3, 3, 0, 0, 5, 8],
         [0, 1, 7, 2, 8, 5],
         [6, 3, 4, 4, 6, 0],
         [6, 3, 3, 0, 7, 2]],

        [[3, 7, 3, 2, 1, 6],
         [6, 3, 8, 3, 0, 0],
         [5, 3, 6, 7, 8, 7],
         [8, 1, 3, 5, 7, 6],
         [5, 0, 5, 0, 7, 8]],

        [[4, 5, 0, 3, 1, 3],
         [4, 6, 8, 5, 6, 3],
         [2, 6, 6, 3, 5, 4],
         [7, 1, 2, 0, 7, 2],
         [7, 7, 8, 7, 2, 2]]],


       [[[7, 3, 7, 4, 8, 5],
         [7, 2, 4, 3, 4, 3],
         [0, 5, 3, 6, 0, 3],
         [4, 2, 7, 8, 0, 8],
         [3, 6, 6, 6, 7, 5]],

        [[2, 4, 7, 5, 1, 3],
         [8, 1, 1, 4, 6, 0],
         [8, 7, 3, 5, 1, 7],
         [7, 3, 8, 0, 7, 7],
         [8, 1, 6, 7, 8, 6]],

        [[1, 3, 7, 7, 1, 4],
         [5, 2, 1, 1, 5, 5],
         [5, 4, 3, 2, 1, 6],
         [8, 3, 2, 6, 7, 8],


In [45]:
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1]=9
output [1:4,1:4]= z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Math in Numpy

In [59]:
a = np.random.randint(9, size= 56)
print(a)

[6 6 4 4 4 7 4 2 7 6 7 2 6 5 6 0 3 6 2 8 4 1 3 1 0 1 5 7 6 2 8 4 1 1 7 0 0
 8 3 6 4 0 7 4 4 5 2 8 5 6 4 2 6 6 0 1]


In [60]:
a + 2

array([ 8,  8,  6,  6,  6,  9,  6,  4,  9,  8,  9,  4,  8,  7,  8,  2,  5,
        8,  4, 10,  6,  3,  5,  3,  2,  3,  7,  9,  8,  4, 10,  6,  3,  3,
        9,  2,  2, 10,  5,  8,  6,  2,  9,  6,  6,  7,  4, 10,  7,  8,  6,
        4,  8,  8,  2,  3])

In [61]:
a - 2

array([ 4,  4,  2,  2,  2,  5,  2,  0,  5,  4,  5,  0,  4,  3,  4, -2,  1,
        4,  0,  6,  2, -1,  1, -1, -2, -1,  3,  5,  4,  0,  6,  2, -1, -1,
        5, -2, -2,  6,  1,  4,  2, -2,  5,  2,  2,  3,  0,  6,  3,  4,  2,
        0,  4,  4, -2, -1])

In [62]:
a * 2

array([12, 12,  8,  8,  8, 14,  8,  4, 14, 12, 14,  4, 12, 10, 12,  0,  6,
       12,  4, 16,  8,  2,  6,  2,  0,  2, 10, 14, 12,  4, 16,  8,  2,  2,
       14,  0,  0, 16,  6, 12,  8,  0, 14,  8,  8, 10,  4, 16, 10, 12,  8,
        4, 12, 12,  0,  2])

In [64]:
a ** 23

array([ 789730223053602816,  789730223053602816,      70368744177664,
            70368744177664,      70368744177664, 8922003266371364727,
            70368744177664,             8388608, 8922003266371364727,
        789730223053602816, 8922003266371364727,             8388608,
        789730223053602816,   11920928955078125,  789730223053602816,
                         0,         94143178827,  789730223053602816,
                   8388608,                   0,      70368744177664,
                         1,         94143178827,                   1,
                         0,                   1,   11920928955078125,
       8922003266371364727,  789730223053602816,             8388608,
                         0,      70368744177664,                   1,
                         1, 8922003266371364727,                   0,
                         0,                   0,         94143178827,
        789730223053602816,      70368744177664,                   0,
       8922003266371

In [66]:
np.sin(a)


array([-0.2794155 , -0.2794155 , -0.7568025 , -0.7568025 , -0.7568025 ,
        0.6569866 , -0.7568025 ,  0.90929743,  0.6569866 , -0.2794155 ,
        0.6569866 ,  0.90929743, -0.2794155 , -0.95892427, -0.2794155 ,
        0.        ,  0.14112001, -0.2794155 ,  0.90929743,  0.98935825,
       -0.7568025 ,  0.84147098,  0.14112001,  0.84147098,  0.        ,
        0.84147098, -0.95892427,  0.6569866 , -0.2794155 ,  0.90929743,
        0.98935825, -0.7568025 ,  0.84147098,  0.84147098,  0.6569866 ,
        0.        ,  0.        ,  0.98935825,  0.14112001, -0.2794155 ,
       -0.7568025 ,  0.        ,  0.6569866 , -0.7568025 , -0.7568025 ,
       -0.95892427,  0.90929743,  0.98935825, -0.95892427, -0.2794155 ,
       -0.7568025 ,  0.90929743, -0.2794155 , -0.2794155 ,  0.        ,
        0.84147098])

In [ ]:
#Linear algebra

In [69]:
a = np.full((2,3), 6)
print(a)
b = np.full((3,2),2)
print(b)

[[6 6 6]
 [6 6 6]]
[[2 2]
 [2 2]
 [2 2]]


In [70]:
np.matmul(a,b)

array([[36, 36],
       [36, 36]])

Statistics

In [74]:
stats = np.array ((1,2,3,4,5,6,7,8,9))
print(stats)

[1 2 3 4 5 6 7 8 9]


In [76]:
np.min(stats)

1

In [77]:
np.max(stats)

9

In [78]:
np.mean(stats)

5.0

In [83]:
np.var(stats)

6.666666666666667

Reorganizing Arrays

In [82]:
before = np.array ([[1,2,3,4],[5,6,7,8]])

after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
